config/routes.rb
Hiteligenyles::Application.routes.draw do
  get "mortgages/new"

  get "mortgages/confirm"

  resources :claims

  root to: 'static_pages#home'

  match '/help', to: 'static_pages#help'

  match '/about', to: 'static_pages#about'

  match '/commonform', to: 'claims#new'

  match '/mortgageform', to: 'mortgages#new'

end

app/models/claim.rb
class Claim < ActiveRecord::Base
  attr_accessible :birth, :claimmoney, :duration, :mothersname, :name, :salary, :mortgage

  VALID_NAME_REGEX = /\A([A-Z]\w+)( [A-Z]\w+)+\z/i
  validates :name, presence: true, length: {maximum: 50}, format: {with: VALID_NAME_REGEX}
  validates :mothersname, presence: true, length: {maximum: 50}, format: {with: VALID_NAME_REGEX}
  validates :birth, presence: true
  validates :salary, presence: true
  validates :claimmoney, presence: true
  validates :duration, presence: true
end

app/models/mortgage.rb
class Mortgage < ActiveRecord::Base
  attr_accessible :addexpense, :addincome, :city, :door, :floor, :number, :postcode, :street, :value, :housemortgage

  validate :postcode, presence: true, length: {minimum: 4, maximum: 4}
  validate :city, presence: true
  validate :street, presence: true
  validate :number, presence: true
  validate :value, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/claims_controller.rb
class ClaimsController < ApplicationController
  def new
    @claim = Claim.new
  end

  def create
    @claim = Claim.new(params[:claim])
    if @claim.save
      if @claim.mortgage?
        redirect_to mortgageform_path
      else
        flash[:success] = "Kerelem elkuldve"
        redirect_to @claim
      end
    else
      render 'new'
    end
  end

  def show
    @claim = Claim.find(params[:id])
  end
end

app/controllers/mortgages_controller.rb
class MortgagesController < ApplicationController
  def new
  end

  def show
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Bankinfo projekt"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/helpers/mortgage_helper.rb
module MortgageHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/claims/new.html.erb
<%= provide(:title, 'Adatok rogzitese') %>
<h1>Adatok rögzítése</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@claim) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :name, "Név" %>
        <%= f.text_field :name %>

        <%= f.label :mothersname, "Anyja neve" %>
        <%= f.text_field :mothersname %>

        <%= f.label :birth, "Születés" %>
        <%= f.date_select :birth, :start_year => Time.now.year - 100,
                          :end_year => Time.now.year %>

        <%= f.label :salary, "Fizetés(havi)" %>
        <%= f.text_field :salary %>

        <%= f.label :claimmoney, "Igényelt összeg" %>
        <%= f.text_field :claimmoney %>

        <%= f.label :duration, "Futamidő" %>
        <%= f.text_field :duration %>

        <%= f.label :mortgage, "Jelzálog?" %>
        <%= f.check_box :mortgage %>

        </br>

        <%= f.submit "OK", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/claims/show.html.erb
<% provide(:title, "Visszajelzes") %>
<h1>Adatok</h1>

<div class="container hero-unit">
  <ul>
    <li>Név: <%= @claim.name %></li>
    <li>Anyja neve: <%= @claim.mothersname %></li>
    <li>Születési idő: <%= @claim.birth %></li>
    <li>Fizetés: <%= @claim.salary %> HUF/hó</li>
    <li>Igényelt összeg: <%= @claim.claimmoney %> HUF</li>
    <li>Futamidő: <%= @claim.duration %> hónap</li>
    <li>Nem jelzálog</li>
    <li><h3>Törlesztő részlet: <%= (@claim.claimmoney)/(@claim.duration) %> HUF/hó</h3></li>
  </ul>
</div>

app/views/layouts/_nav.html.erb
<nav>
  <ul class="nav nav-tabs nav-stacked pull-left">
    <li><%= link_to "Kezdő oldal", root_path %></li>
    <li><%= link_to "Hitel igénylés", commonform_path %></li>
    <li><%= link_to "Segitség", help_path %></li>
    <li><%= link_to "Rólunk", about_path %></li>
  </ul>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/nav' %>
<div class="container">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/mortgages/new.html.erb
<%= provide(:title, "Jelzalog") %>
<h1>Jelzálog</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@mortgage) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :postcode, "Irányítószám" %>
        <%= f.text_field :postcode %>

        <%= f.label :city, "Város" %>
        <%= f.text_field :city %>

        <%= f.label :number, "Házszám" %>
        <%= f.text_field :number %>

        <%= f.label :floor, "Emelet" %>
        <%= f.text_field :floor %>

        <%= f.label :door, "Ajtó" %>
        <%= f.text_field :door %>

        <%= f.label :value, "Ingatlan értéke" %>
        <%= f.text_field :value %>

        <%= f.label :addincome, "Ingatlan bevételek" %>
        <%= f.text_field :addincome %>

        <%= f.label :addexpense, "Ingatlan kiadások" %>
        <%= f.text_field :addexpense %>

        <%= f.label :housemortgage, "Lakáscélú?" %>
        <%= f.check_box :housemortgage %>

        </br>

        <%= f.submit "OK", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/mortgages/show.html.erb
<h1>Mortgage#show</h1>
<p>Find me in app/views/mortgage/show.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if @claim.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(@claim.errors.count, "error") %>.
      </div>
      <ul>
        <% @claim.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'Rolunk') %>
<h1>Rólunk</h1>
<h2>
  A projekt készítői: </h2>
<h3>
  Buzsáky Andrea</br>
  Kiss Tímea</br>
  Kővári Zsuzsanna</br>
  Németh Imre
</h3>

app/views/static_pages/help.html.erb
<% provide(:title, 'Segitseg') %>
<h1>Segítség</h1>
<h2>
  Töltsd ki az űrlapot :)
</h2>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Üdvözlet!</h1>

  <h2>
    A Bankinfó projekt nyitó oldala.
  </h2>
  <%= link_to "Hitel igénylés", commonform_path, class: "btn btn-large btn-primary" %>
</div>